// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr3a4T_Xq79NOfvzPYenEAe3QvMcsvUd8',
    appId: '1:1017519908947:web:a275f6d395943e8e6a3ea6',
    messagingSenderId: '1017519908947',
    projectId: 'crypto-list-app-002',
    authDomain: 'crypto-list-app-002.firebaseapp.com',
    storageBucket: 'crypto-list-app-002.firebasestorage.app',
    measurementId: 'G-Y3RKYD61M5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIJuxTz5oZd36MfO5vd3NaDExvcTiJ-Hc',
    appId: '1:1017519908947:android:bfe8febf29d750736a3ea6',
    messagingSenderId: '1017519908947',
    projectId: 'crypto-list-app-002',
    storageBucket: 'crypto-list-app-002.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE9JWuPdpl_KzgJ114PQCqn_gdxF7Mmac',
    appId: '1:1017519908947:ios:235d9fdd1fce7c506a3ea6',
    messagingSenderId: '1017519908947',
    projectId: 'crypto-list-app-002',
    storageBucket: 'crypto-list-app-002.firebasestorage.app',
    iosBundleId: 'com.cryptoguys.cryptoCoinsList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE9JWuPdpl_KzgJ114PQCqn_gdxF7Mmac',
    appId: '1:1017519908947:ios:235d9fdd1fce7c506a3ea6',
    messagingSenderId: '1017519908947',
    projectId: 'crypto-list-app-002',
    storageBucket: 'crypto-list-app-002.firebasestorage.app',
    iosBundleId: 'com.cryptoguys.cryptoCoinsList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAr3a4T_Xq79NOfvzPYenEAe3QvMcsvUd8',
    appId: '1:1017519908947:web:0d6a66e12cf943fc6a3ea6',
    messagingSenderId: '1017519908947',
    projectId: 'crypto-list-app-002',
    authDomain: 'crypto-list-app-002.firebaseapp.com',
    storageBucket: 'crypto-list-app-002.firebasestorage.app',
    measurementId: 'G-F4NVTFM187',
  );
}
